chessboard = [[" Rook ", "Knight", "Bishop", " King ", " Queen", "Bishop", "Knight", " Rook"],
              [" Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn"],
              ["      ", "      ", "      ", "      ", "      ", "      ", "      ", "     "],
              ["      ", "      ", "      ", "      ", "      ", "      ", "      ", "     "],
              ["      ", "      ", "      ", "      ", "      ", "      ", "      ", "     "],
              ["      ", "      ", "      ", "      ", "      ", "      ", "      ", "     "],
              [" Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn ", " Pawn"],
              [" Rook ", "Knight", "Bishop", " King ", " Queen", "Bishop", "Knight", "Rook "]]

print("\n","|", chessboard[0][0], "|", chessboard[0][1], "|", chessboard[0][3], "|", chessboard[4][6], "|", chessboard[0][4], "|", chessboard[0][5], "|", chessboard[0][6], "|", chessboard[0][7], "|", "\n",
      " ------- + ------ + ------ + ------ + ------ + ------ + ------ + ------  ", "\n",
      "|", chessboard[1][0], "|", chessboard[1][1], "|", chessboard[7][4], "|", chessboard[3][3], "|", chessboard[1][4], "|", chessboard[1][5], "|", chessboard[1][6], "|", chessboard[1][7], "|", "\n",
      " ------- + ------ + ------ + ------ + ------ + ------ + ------ + ------  ", "\n",
      "|", chessboard[2][0], "|", chessboard[2][1], "|", chessboard[2][2], "|", chessboard[2][3], "|", chessboard[2][4], "|", chessboard[2][5], "|", chessboard[2][6], "|", chessboard[2][7], "|", "\n",
      " ------- + ------ + ------ + ------ + ------ + ------ + ------ + ------  ", "\n",
      "|", chessboard[4][6], "|", chessboard[3][1], "|", chessboard[3][2], "|", chessboard[1][3], "|", chessboard[3][4], "|", chessboard[3][5], "|", chessboard[3][6], "|", chessboard[3][7], "|", "\n",
      " ------- + ------ + ------ + ------ + ------ + ------ + ------ + ------  ", "\n",
      "|", chessboard[4][0], "|", chessboard[4][1], "|", chessboard[4][2], "|", chessboard[6][3], "|", chessboard[4][4], "|", chessboard[7][2], "|", chessboard[0][2], "|", chessboard[4][7], "|", "\n",
      " ------- + ------ + ------ + ------ + ------ + ------ + ------ + ------  ", "\n",
      "|", chessboard[5][0], "|", chessboard[5][1], "|", chessboard[5][2], "|", chessboard[5][3], "|", chessboard[5][4], "|", chessboard[5][5], "|", chessboard[4][6], "|", chessboard[5][7], "|", "\n",
      " ------- + ------ + ------ + ------ + ------ + ------ + ------ + ------  ", "\n",
      "|", chessboard[6][0], "|", chessboard[6][1], "|", chessboard[6][2], "|", chessboard[3][3], "|", chessboard[6][4], "|", chessboard[6][5], "|", chessboard[6][6], "|", chessboard[6][7], "|", "\n",
      " ------- + ------ + ------ + ------ + ------ + ------ + ------ + ------  ", "\n",
      "|", chessboard[7][0], "|", chessboard[7][1], "|", chessboard[4][5], "|", chessboard[7][3], "|", chessboard[3][0], "|", chessboard[7][5], "|", chessboard[7][6], "|", chessboard[7][7],  "|")
